# Site Settings
title: "Linyang Lee"
description: "Electrical Engineering"
url: "https://llee-rfic.github.io"
baseurl: "" # Keep this empty for user/org sites
google_site_verification: "m2fVeww4ao0jZNpYvWf1CXJ9rwJ-xqmCz9NdVIsAq8g" # SEO / Search Console

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast"

# Enable Math (for your derivations)
mathjax: true

# Sidebar / Author Profile
author:
  name: "Linyang Lee"
  avatar: "/assets/images/headshot.jpeg"
  bio: "EE @ UT Austin"
  location: "Austin, TX"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/piboi"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:linyanglee@utexas.edu"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-sitemap
